### ISSUE TITLE
Failing on packageVersion("aws.athena")

### ISSUE THREAD

**Issue by rgustavs** [cloudyr/roto.athena#2]
Thanks for a promising package

Trying to follow your instructions and get the following 
`
> library(roto.athena) # hrbrmstr/roto.athena on gh or gl
> library(tidyverse) # b/c it rocks
> packageVersion("aws.athena")
Error in packageVersion("aws.athena") : package ‘aws.athena’ not found
> `

Any advice on what is missing? Many thanks

**Comment by hrbrmstr** [comment]
fixed the docs. the old dev name was `aws.athena` and it's still lying around on my home systems. #ty
